name: Bacons Helper OBS Companion Pull Request
run-name: ${{ github.event.pull_request.title }} build

on:
  pull_request:
    branches: [main, master]

permissions:
  contents: read

concurrency:
  group: bh-obs-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build:
    name: Build Packages
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
